import { signUpApplicant } from '../fixtures/signup'
import { expect, test } from '@playwright/test'
import { grantForm } from '../fixtures/grant-form'

test('budget and activities are calculated, validated, saved and readable after submission', async ({ page, browser, baseURL }) => {
  test.setTimeout(120000)
  expect((await page.request.post('/api/admin/login', { data: { email: 'root@example.test', password: 'Root-test-only-2026!' } })).ok()).toBe(true)
  const agency = (await (await page.request.post('/api/admin/agencies', { data: { nameEn: 'Grant elements agency', nameFr: 'Organisme des éléments' } })).json()).agency
  const key = (await (await page.request.post('/api/admin/integration-tokens', { data: { name: 'Grant elements', agencyId: agency.id } })).json()).token
  const machine = await browser.newContext({ baseURL, ignoreHTTPSErrors: true, extraHTTPHeaders: { Authorization: `Bearer ${key}` } })
  const applicantContext = await browser.newContext({ baseURL, ignoreHTTPSErrors: true, extraHTTPHeaders: { Origin: baseURL! } })
  try {
    const program = (await (await machine.request.post('/api/government/programs', { data: { agencyId: agency.id, nameEn: 'Community', nameFr: 'Communauté' } })).json()).program
    const stream = (await (await machine.request.post('/api/government/streams', { data: { programId: program.id, nameEn: 'Projects', nameFr: 'Projets' } })).json()).stream
    const surveyRequest = await machine.request.post('/api/government/surveys', { data: { agencyId: agency.id, definition: grantForm() } })
    expect(surveyRequest.ok(), await surveyRequest.text()).toBe(true)
    const survey = (await surveyRequest.json()).survey
    const callId = (await (await machine.request.post('/api/government/calls', { data: { streamId: stream.id, nameEn: 'Grant plan', nameFr: 'Plan de financement', startDate: '2020-01-01', endDate: '2099-12-31' } })).json()).id
    expect((await machine.request.put(`/api/government/calls/${callId}/forms`, { data: { forms: [{ surveyId: survey.id, revision: survey.revision }] } })).ok()).toBe(true)
    expect((await machine.request.patch(`/api/government/calls/${callId}/publication`, { data: { published: true } })).ok()).toBe(true)
    const applicant = await applicantContext.newPage()
    expect((await signUpApplicant(applicant.request, { data: { name: 'Grant applicant', email: `grant-${Date.now()}@example.test`, password: 'Applicant-test-only-2026!' } })).ok()).toBe(true)
    const userId = (await (await applicant.request.get('/api/session')).json()).user.id
    const organization = (await (await applicant.request.post('/api/organizations', { data: { name: 'Grant organization' } })).json()).organization
    expect((await applicant.request.patch(`/api/organizations/${organization.id}/members/${userId}`, { data: { permissions: ['user', 'admin', 'application:manager', 'form:manager'] } })).ok()).toBe(true)
    await applicant.goto(`/organizations/${organization.id}?section=funding`)
    await applicant.locator('.record-summary').filter({ has: applicant.getByRole('heading', { name: 'Grant plan', exact: true }) }).getByRole('button', { name: 'Start application' }).click()
    await applicant.getByRole('button', { name: 'Add a cost', exact: true }).click()
    await applicant.getByRole('combobox', { name: 'Cost category / line item' }).selectOption('salary')
    await applicant.getByRole('textbox', { name: 'Cost subsection' }).fill('Delivery')
    await applicant.getByRole('textbox', { name: 'Description', exact: false }).first().fill('Instructor costs')
    await applicant.getByRole('textbox', { name: 'Total cost' }).fill('1500')
    await applicant.getByRole('textbox', { name: 'Program funding', exact: false }).fill('1000')
    await applicant.getByRole('button', { name: 'Add a funding source' }).click()
    await applicant.getByRole('combobox', { name: 'Funding type / source' }).selectOption('province')
    await applicant.getByRole('textbox', { name: 'Amount', exact: false }).fill('500')
    await applicant.getByRole('button', { name: 'Add an activity' }).click()
    await applicant.getByRole('button', { name: 'Check responses' }).click()
    await expect(applicant.getByText('Complete this required value.').first()).toBeVisible()
    await applicant.getByRole('textbox', { name: 'Activity name' }).fill('Training')
    await applicant.getByRole('textbox', { name: 'What will you do?' }).fill('Deliver workshops')
    await applicant.getByRole('textbox', { name: 'Expected results' }).fill('Train 20 people')
    await applicant.getByRole('textbox', { name: 'Start date' }).fill('2028-04-01')
    await applicant.getByRole('textbox', { name: 'End date' }).fill('2028-06-30')
    await applicant.getByRole('checkbox', { name: 'Skills development' }).focus()
    await applicant.keyboard.press('Space')
    await expect(applicant.getByRole('checkbox', { name: 'Skills development' })).toBeChecked()
    await expect(applicant.getByRole('checkbox', { name: 'Skills development' })).not.toHaveAttribute('required', '')
    await applicant.getByRole('checkbox', { name: 'Applicant organization' }).focus()
    await applicant.keyboard.press('Space')
    await expect(applicant.getByRole('checkbox', { name: 'Applicant organization' })).toBeChecked()
    await applicant.getByRole('textbox', { name: 'Project rationale' }).fill('Our project addresses local needs.\nIt supports accessible training.')
    await expect(applicant.getByRole('textbox', { name: 'Project rationale' })).toHaveJSProperty('tagName', 'TEXTAREA')
    await expect(applicant.getByRole('textbox', { name: 'Project rationale' })).toHaveAttribute('required', '')
    await applicant.getByRole('checkbox', { name: 'Training services' }).focus(); await applicant.keyboard.press('Space')
    await expect(applicant.getByRole('checkbox', { name: 'Training services' })).not.toHaveAttribute('required', '')
    if (!await applicant.getByRole('checkbox', { name: 'North', exact: true }).isVisible()) await applicant.getByRole('button', { name: /Regions \(Required\) — 0/ }).click()
    await applicant.getByRole('checkbox', { name: 'North', exact: true }).focus(); await applicant.keyboard.press('Space')
    await applicant.getByRole('checkbox', { name: 'South', exact: true }).focus(); await applicant.keyboard.press('Space')
    await applicant.getByRole('combobox', { name: 'Delivery method' }).selectOption('online')
    await applicant.getByRole('button', { name: 'Add row', exact: true }).click()
    await expect(applicant.getByRole('textbox', { name: 'Year one' })).toHaveAttribute('inputmode', 'decimal')
    await applicant.getByRole('textbox', { name: 'Year one' }).fill('0.1')
    await applicant.getByRole('textbox', { name: 'Year two' }).fill('0.2')
    await expect(applicant.locator('output').filter({ hasText: '0.3' })).toHaveCount(1)
    await applicant.getByRole('button', { name: 'Add row', exact: true }).click()
    await applicant.getByRole('textbox', { name: 'Year one' }).nth(1).fill('1')
    await expect(applicant.locator('output').filter({ hasText: '1.1' })).toHaveCount(1)
    await applicant.getByRole('button', { name: 'Remove row', exact: true }).nth(1).click()
    await expect(applicant.locator('output').filter({ hasText: '1.1' })).toHaveCount(0)
    await applicant.getByRole('button', { name: 'Add a cost', exact: true }).click()
    const second = applicant.locator('.grant-entry').filter({ hasText: 'Cost 2' })
    await second.getByRole('combobox', { name: 'Cost category / line item' }).selectOption('admin')
    await second.getByRole('textbox', { name: 'Cost subsection' }).fill('Overhead')
    await second.getByRole('textbox', { name: 'Description' }).fill('Administration')
    await second.getByRole('textbox', { name: 'Total cost' }).fill('100')
    await expect(second.getByRole('textbox', { name: 'Calculated program funding' })).toHaveValue('100.00')
    await expect(second.getByRole('textbox', { name: 'Calculated program funding' })).toHaveAttribute('readonly', '')
    await applicant.screenshot({ path: '.agent/reports/grants/portal-desktop.png', fullPage: true })
    await applicant.setViewportSize({ width: 390, height: 844 })
    await applicant.screenshot({ path: '.agent/reports/grants/portal-mobile.png', fullPage: true })
    const overflow = await applicant.evaluate(() => ({ viewport: window.innerWidth, width: document.documentElement.scrollWidth, elements: [...document.querySelectorAll('*')].filter(element => element.getBoundingClientRect().right > window.innerWidth + 1).slice(0, 8).map(element => [element.tagName, element.className, element.getBoundingClientRect().width]) }))
    expect(overflow.width, JSON.stringify(overflow)).toBeLessThanOrEqual(overflow.viewport)
    await applicant.getByRole('button', { name: 'Check responses' }).click()
    await expect(applicant.getByText('The responses are valid.')).toBeVisible()
    await applicant.getByRole('button', { name: 'Save draft' }).click()
    const responseId = applicant.url().split('/').at(-1)!
    const response = (await (await applicant.request.get(`/api/organizations/${organization.id}/responses/${responseId}`)).json()).response
    expect(JSON.parse(response.items[0].answers.services)).toEqual(['training'])
    expect(JSON.parse(response.items[0].answers.regions)).toEqual(['north', 'south'])
    const budget = JSON.parse(response.items[0].answers.budget)
    expect(budget.rows[0]).toMatchObject({ totalCost: '1500.00', programFunding: '1000.00', otherFunding: [{ subtypeId: 'province', amount: '500.00' }] })
    expect(budget.rows[1].programFunding).toBe('100.00')
    expect((await applicant.request.post(`/api/organizations/${organization.id}/responses/${responseId}/submit`, { data: { expectedRevision: response.revision, balanceRevision: null, warningsAcknowledged: true } })).ok()).toBe(true)
    await applicant.reload()
    await expect(applicant.getByText('Training', { exact: true })).toBeVisible()
    await expect(applicant.getByRole('textbox', { name: 'Activity name' })).toHaveCount(0)
    await expect(applicant.getByRole('button', { name: 'Add a cost', exact: true })).toHaveCount(0)
    await expect(applicant.getByText(/"version":1/)).toHaveCount(0)
    await expect(applicant.locator('dd').filter({ hasText: 'Our project addresses local needs.' })).toHaveCSS('white-space', 'pre-wrap')
    await expect(applicant.getByText('North, South', { exact: true })).toBeVisible()
    await applicant.locator('gcds-lang-toggle').getByRole('link').click()
    await expect(applicant.getByText('Personnel / Salaires', { exact: true })).toBeVisible()
    await expect(applicant.getByText('Training', { exact: true })).toBeVisible()
    await applicant.screenshot({ path: '.agent/reports/grants/portal-submitted-fr.png', fullPage: true })
  } finally { await machine.close(); await applicantContext.close() }
})
